### ISSUE TITLE
ghc-lib-parser-8.8.2 out of bounds for ghc-syntax-highlighter-0.0.5.0

### ISSUE THREAD

**Issue by DanBurton** [mrkkrp/ghc-syntax-highlighter#14]
I'm going to bump ghc-syntax-highlighter out of the stackage nightly builds since we are imminently switching to ghc 8.2.2 in prep for lts 15. Feel free to ping me about getting it back in once it has been updated.

**Comment by mrkkrp** [comment]
@DanBurton the package has been updated and I released a new revision.

**Comment by DanBurton** [comment]
@mrkkrp thanks! I've opened a PR to have it restored to the Stackage nightly build plan. https://github.com/commercialhaskell/stackage/pull/5091
