### ISSUE TITLE
ifdefs on a case expression makes "tokenizeHaskellLoc" return "Nothing"

### ISSUE THREAD

**Issue by resolritter** [mrkkrp/ghc-syntax-highlighter#19]
Sorry for the possibly wrong issue title, as I am quite ignorant about Haskell ATM so could've not specified it better.

Anyways, I'm finding the following expression does not lex properly (please ignore the missing definitions as they are not relevant). More specifically, it's the `nargs {...}` case expression part; removing it seems to fix the problem.

```haskell
{-# LANGUAGE NamedFieldPuns    #-}
{-# LANGUAGE TemplateHaskell   #-}
{-# LANGUAGE CPP               #-}

functionImplementation :: Name -> Q ([ArgType], Exp)
functionImplementation functionName = do
    fInfo <- reify functionName
    nargs <- mapM classifyArgType $ case fInfo of
#if __GLASGOW_HASKELL__ < 800
            VarI _ functionType _ _ ->
#else
            VarI _ functionType _ ->
#endif
                determineNumberOfArguments functionType

            x ->
                error $ "Value given to function is (likely) not the name of a function.\n" <> show x

    e <- topLevelCase nargs
    return (nargs, e)
```

[Full source](https://github.com/neovimhaskell/nvim-hs/blob/20eb262f4a171586a40027c12478a0fee319bb6a/library/Neovim/API/TH.hs#L478)

**Comment by mrkkrp** [comment]
My guess is that it's' because Haskell parser is not supposed to deal with CPP.

**Comment by resolritter** [comment]
The other pre-processor definitions throughout the file are apparently fine. It's only specifically inside the case statements that it breaks.

Although, thinking more about it, the problem shouldn't come from this library... It'd instead be a "problem" on GHC's implementation itself.

I've opened the MR at #20 which will be closing this.
