### ISSUE TITLE
File header pragmas not recognised

### ISSUE THREAD

**Issue by b-mehta** [mrkkrp/ghc-syntax-highlighter#4]
File header pragmas such as `LANGUAGE` and `OPTIONS_GHC` are given comment tokens instead of pragma tokens:

```
> :set -XOverloadedStrings
> tokenizeHaskellLoc "{-# OPTIONS_GHC -fno-warn-unused-matches #-}"
Just [(CommentTok,Loc 1 1 1 45)]
> tokenizeHaskellLoc "{-# LANGUAGE ScopedTypeVariables #-}"
Just [(CommentTok,Loc 1 1 1 37)]
> tokenizeHaskellLoc "{-# INLINE func #-}"
Just [(PragmaTok,Loc 1 1 1 11),(VariableTok,Loc 1 12 1 16),(PragmaTok,Loc 1 17 1 20)]
```

I can't tell if this error stems from the ghc lexer or not - I don't understand it well enough.

**Comment by mrkkrp** [comment]
That’s how the lexer of GHC seems to work. Not sure what can be done about this.

**Comment by b-mehta** [comment]
Can this be considered a bug in the GHC lexer? It seems unfortunate that these pragmas are not coloured correctly.

**Comment by mrkkrp** [comment]
We can try to open a ticket about this.
