### ISSUE TITLE
VariableTok token too broad

### ISSUE THREAD

**Issue by goolord** [mrkkrp/ghc-syntax-highlighter#7]
I don't know if this is a limitation of how ghc lexes haskell, but the resulting image is undesirable for syntax highlighting imo. Without highlighting `VariableTok` , it just looks barren. 

![IMG](https://i.imgur.com/hkCc7jb.png)
(note how each function in the body of `tokenizeHaskell` is highlighted as part of the VariableTok group)
Could `VariableTok` be meaningfully broken up into smaller tokens?

**Comment by mrkkrp** [comment]
I think they all are `L.ITvarid` in GHC AST, so there is no way to classify them more precisely:

https://github.com/mrkkrp/ghc-syntax-highlighter/blob/master/GHC/SyntaxHighlighter.hs#L295

How exactly would you like to break `VariableTok` into smaller tokens? What would be the criteria for this "sub-classification"?

**Comment by goolord** [comment]
yeah, after messing around with it, it does indeed seem like a limitation of how ghc lexes haskell. what i was looking for is tokenizing identifiers only where they are defined, and not where they are used, but I suppose i can just supplement this with vim's regex syntax highlighting

**Comment by neongreen** [comment]
At least declarations (`foo ::` and `(&$^) ::`) could probably be detected by looking at `Loc`s.

**Comment by neongreen** [comment]
Well, not reliably though:

```haskell
module Foo where

  bar :: ...
```
